spring:
   profiles:
      active:
        - dev
---
server:
  port: 8101

spring:
  profiles: dev
  application:
      name: config-test-client

eureka:
 client:
  service-url:
    defaultZone: http://admin:user@localhost:7001/eureka
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: config-test-client

eureka:
 client:
  service-url:
    defaultZone: http://admin:user@localhost:7001/eureka